### ISSUE TITLE
profiles query changes order of profiles in response

### ISSUE THREAD

**Issue by krystxf** [lens-protocol/api-examples#108]
# Problem
The `profiles` query will return the profiles in a different order than they are in the request. It seems like a feature, but I'm not sure if it's useful at all.

## Query
```graphQL
query getProfiles {
  profiles(request: { profileIds: ["0x09", "0x05"] }) {
    items {
      id
    }
  }
}

```

## Response
```json
{
  "data": {
    "profiles": {
      "items": [
        {
          "id": "0x05"
        },
        {
          "id": "0x09"
        }
      ]
    }
  }
}
```
(in request  ["0x09", "0x05"], in response  ["0x05", "0x09"])

# Solution
Maybe there could be a `sort` parameter

**Comment by juangm** [comment]
Hi,

It appears that the issue has been successfully resolved. I am proceeding to close this ticket accordingly.
