### ISSUE TITLE
Field contractAddress is not defined by type UnknownFollowModuleRedeemParams in createFollowTypedData query

### ISSUE THREAD

**Issue by nezz0746** [lens-protocol/api-examples#110]
# Problem
When running the createFollowTypedData query, the following error is being returned:

```
"Field 'contractAddress' is not defined by type 'UnknownFollowModuleRedeemParams'"
```

This suggests that the _contractAddress_ field is not being recognized as part of the UnknownFollowModuleRedeemParams type in the GraphQL schema.

on Mumbai Sandbox Env

# My Query

```graphql
mutation CreateFollowTypedData {
  createFollowTypedData(
    request: {
      follow: [
        {
          profile: "${profileId}",
          followModule: {
            unknownFollowModule: {
              data: "[MY_DATA]"
            }
          }
        }
      ]
    }
  ) {
    id
    ...
  }
}

```

Let me know if you have any further questions or requests.

**Comment by joshstevens19** [comment]
fix in release on thursday
