### ISSUE TITLE
totalCount in the pageInfo of GetPublications query results is always null

### ISSUE THREAD

**Issue by daoleno** [lens-protocol/api-examples#118]
When I run a GraphQL query to fetch publications, the totalCount field in the pageInfo object is always null.

## Steps to reproduce
Run query example in https://docs.lens.xyz/docs/get-publications
```
"pageInfo": {
        "prev": "{\"entityIdentifier\":\"0x05-0x11b0\",\"timestamp\":1673099188,\"cursorDirection\":\"BEFORE\"}",
        "next": "{\"entityIdentifier\":\"0x05-0x11a7\",\"timestamp\":1673012707,\"cursorDirection\":\"AFTER\"}",
        "totalCount": null
      }
```

**Comment by joshstevens19** [comment]
Hey we removing dynamic total counts throughout the API, in January we going to purely focus on performance and we came to the conclusion showing the total amount normally is not needed for a UI and UX to work well (in a case where explore most likely is 10000+ showing that number doesn’t help UX wise), as long as it knows if it has more items that’s enough. Dynamic count are expensive when the data is growing, we have count tables for the normal stuff like comments counts and profile counts and we continue to do count tables for that, but endpoints which can be queried in a dynamic way are going to stop returning that number. For example removing this improved the query 30x. On top of this we want to bring our db size down and make everything easier to be runnable for backend which can be ran without it being super expensive (for the future) Hope it’s not caused to many issues but the benefit outweighs having it
