### ISSUE TITLE
Lens api blocking graphql-codegen versions from 2.16.5

### ISSUE THREAD

**Issue by hixus** [lens-protocol/api-examples#126]
Noticed this when upgrading graphql-codegen to latest 3.21. Running codegen against `https://api.lens.dev` results in `<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n`

Seems last v2 version is also affected (2.16.5). Version 2.3.1 is still functioning. Also `https://api-mumbai.lens.dev` not affected.

**Comment by hixus** [comment]
Seems to be fixed now.

**Comment by joshstevens19** [comment]
Yep we fixed it thanks for raising
