### ISSUE TITLE
Profile following bug

### ISSUE THREAD

**Issue by sleek4** [lens-protocol/api-examples#130]
I followed Phaver app on lens
So tried to verify myself on their guild
An error occurred, that I don't follow Phaver
![Screenshot_20230313-101617_Mises](https://user-images.githubusercontent.com/78409412/224909879-f2e497af-a6f0-4270-889d-83b87527d028.jpg)
![Screenshot_20230313-101627_Mises](https://user-images.githubusercontent.com/78409412/224909883-fa48c751-042c-4add-bc5f-7e4d56742b64.jpg)

**Comment by cesarenaldi** [comment]
This one seems Lenster specific. Try to report it on https://github.com/lensterxyz/lenster
