### ISSUE TITLE
When you get to the end of paging totalCount turns to 0

### ISSUE THREAD

**Issue by joshstevens19** [lens-protocol/api-examples#35]
When you using the after cursor and get to the end the paging works perfectly but then totalCount turns to 0 when you reach the end. This is due to no rows returned so it is not defined!

```
{
  "data": {
    "result": {
      "items": [],
      "pageInfo": {
        "prev": null,
        "next": null,
        "totalCount": 0
      }
    }
  }
}
```

this will be the case with all paging!

**Comment by juangm** [comment]
Closing the issue as the field `totalCount` was removed from pagination.
