### ISSUE TITLE
Support for EIP1271 smart wallets

### ISSUE THREAD

**Issue by michaelvogt** [lens-protocol/api-examples#59]
Offering a good user experience in a DAPP around wallet interactions is really hard with browser plugin based wallets, and nearly impossible on mobile. Having the ability to integrate a wallet into the app itself helps tremendously to improve the situation.

Problem is, that the authentication process of the Lenas api doesn't accept the challenge signed with such a smart contract based wallet. The one I tried it with was the Sequence wallet: https://sequence.build/
Specific signing info can be found here: https://docs.sequence.build/build-with-sequence/sign-message

Supporting this would be highly appreciated

**Comment by joshstevens19** [comment]
as said we want to support this!

**Comment by michaelvogt** [comment]
Looking forward to it :)

**Comment by joshstevens19** [comment]
PR is up probably deploy monday thanks for waiting!

**Comment by michaelvogt** [comment]
Amazing. Thanks a lot. Will check it immediately when available.

**Comment by joshstevens19** [comment]
If I remember in hackathon you had a test app for sequence on GitHub that tried to login in to API (might be making it up).. can you re-share so I can verify that with sequence it works if possible

**Comment by michaelvogt** [comment]
Yes, at some time I had an app that used sequence. As it didn't work, removed it again.
Will add sequence to b.trax to verify your changes.

But I think it was possible to reproduce the problem with a sample program from sequence itself.
https://github.com/0xsequence/demo-dapp

In the screenshot there are several Sign-xxx buttons, which failed before when I remember correctly.

**Comment by joshstevens19** [comment]
Ok thanks

**Comment by joshstevens19** [comment]
deployed

**Comment by michaelvogt** [comment]
Just tried on testnet, resulting in the same error as before

`Variable "$request" got invalid value "0x00050203..." at "request.signature"; Expected type "Signature". Invalid - Byte length must be 65, length is 297`

**Comment by michaelvogt** [comment]
The experimentation page of my app that uses the sequence wallet can be found here:
`https://btraxlayout.netlify.app/testing/setup`

The sequence 'integration' can be found here:
https://github.com/nftCol1ective/frontend/blob/sequence/src/lib/services/ethers-service.js

**Comment by joshstevens19** [comment]
Perfect will look into this tomorrow AM for you and get it working locally then deploy I think this provider doesn’t give a 65 byte signature which is not normal hence why validation throwing! Thanks

**Comment by michaelvogt** [comment]
Thanks, Josh. 
I just invited you to the currently private repository of b.trax to make sure you can have a look at the sources if you want.

Yes, signatures of EIP1271 supporting wallets isn't 65 bytes long per definition - I was told. I tried to understand the info in the EIP doc but failed

**Comment by joshstevens19** [comment]
Thanks a lot! yes gnosis safe is 65 bytes but yeah I’m guessing others depending on the way they sign and if they add the signature together or something.. will use this and do a POV to get it working thanks for the repo invite really helpful

**Comment by michaelvogt** [comment]
Hello Josh. Any progress on this?

**Comment by jheavejimenez** [comment]
hi, I'm having the same problem any smart wallet alternatives we can use off?

**Comment by joshstevens19** [comment]
hey should be supported now sorry for the huge delay got forgotten 👍
