### ISSUE TITLE
Page Info Leading to Refetching the same user nfts for GET_USER_NFTS query in lens api

### ISSUE THREAD

**Issue by siddharthgowda** [lens-protocol/api-examples#79]
So after I have loaded all of my nfts using cursor for the next page and limit parameter for the GET_USER_NFTS  call (https://docs.lens.xyz/docs/get-users-nfts) , I get the next page as {"mumbai": null}.

`pageInfo:
next: "{\"mumbai\":null}"
prev: "{\"mumbai\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21QYXJhbXMiOnsid2FsbGV0QWRkcmVzcyI6IjB4MDZmMjAyOTIzNjhjNGE1MTlhMzgwYTcxMzRiYzM2NmY1OTNlOTZmMyJ9LCJrZXlzIjpbIjE2NTU1OTcxODguMzMxIiwiMTY1NzE0MjY1OS41NTkiXSwid2hlcmUiOnsib3duZXJfb2YiOiIweDA2ZjIwMjkyMzY4YzRhNTE5YTM4MGE3MTM0YmMzNjZmNTkzZTk2ZjMifSwibGltaXQiOjUsIm9mZnNldCI6MCwib3JkZXIiOltdLCJ0b3RhbCI6MTMsInBhZ2UiOjIsInRhaWxPZmZzZXQiOjEsImlhdCI6MTY1OTA1MjI4N30.LDeU2NdRFgX9ePO_M09gwhJNWKsxZblgsmz9muH21L0\"}"
totalCount: 13`

But when I use that cursor to fetch more user nfts it should give nothing back (since all of the nfts have been fetched) but instead it fetches every single nft the user has (I think the object have a null value essentially acts like cursor being null)

This is the new pageInfo object

`pageInfo:
next: "{\"mumbai\":null}"
prev: "{\"mumbai\":null}"
totalCount: 13`

After this if I keep on fetching more it will continue to fetch me all of the nfts in the wallet address again

**Comment by joshstevens19** [comment]
closed should be fixed now
