### ISSUE TITLE
whoMirroredPublicationId results are not in order

### ISSUE THREAD

**Issue by 0xkeivin** [lens-protocol/api-examples#81]
**Current behavior:** Results from https://docs.lens.xyz/docs/get-profiles#get-by-who-has-mirrored-a-publication returned are not in order.

**Suggestion:** To have the results in order (e.g. latest profile who mirrored a publication to be returned at the first result)

**Comment by joshstevens19** [comment]
catching up with this, this is valid fix will be deployed in the next release!
