### ISSUE TITLE
API returns wrong profile stats

### ISSUE THREAD

**Issue by bigint** [lens-protocol/api-examples#82]
![Screenshot 2022-08-02 at 11 37 11 AM](https://user-images.githubusercontent.com/69431456/182303743-cf40112b-703b-4f68-bd89-64cad2acc1dd.png)

Some users have one post but it shows 3 posts 😕 

cc @joshstevens19

**Comment by bigint** [comment]
Example https://lenster.xyz/u/gelato.lens

**Comment by juangm** [comment]
This was already fixed in the API.
