### ISSUE TITLE
"publications:post" command not working, throws "could not detect network" error 

### ISSUE THREAD

**Issue by apurvns** [lens-protocol/api-examples#87]
I am trying to create post . When I run `npm run publications:post` I got below error , I tried to replace LENS_API to sandbox and testnet and equivalent contract addresses, but same result. Login and create profile works fine . 

I checked for possible causes , it says it can be : 

- The node is down/unreachable
- The eth_chainId call fails for some reason
- Your network is down

Its surely not the last one ... Can anyone help here if its me doing wrong or issue with node ?

```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.3)
    at Logger.makeError (/lens/api-examples/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/lens/api-examples/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at JsonRpcProvider.<anonymous> (/lens/api-examples/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:403:23)
    at step (/lens/api-examples/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/lens/api-examples/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/lens/api-examples/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

**Comment by zannis** [comment]
Hello and thanks for raising this, on first look this doesn't seem to be a Lens API issue, rather than an JsonRpc connectivity issue. Which JsonRpcProvider are u using? Have you set an Alchemy node with your own key to the `MUMBAI_RPC_URL` env var?

**Comment by apurvns** [comment]
Hi @zannis 
Thanks for reply. 
I tried both . I first kept it as it is https://rpc-mumbai.matic.today and then I tried with https://polygon-mainnet.g.alchemy.com/v2/MY_KEY

Both time same error . 
It fails at this line in publications/post.ts : 

 `const tx = await lensHub.postWithSig` .

**Comment by apurvns** [comment]
I tried both options as below with contract addresses and Lens API endpoints . 

```
MUMBAI_RPC_URL=https://rpc-mumbai.matic.today # & also tried https://polygon-mainnet.g.alchemy.com/v2/MY_KEY
LENS_API=https://api-mumbai.lens.dev/
LENS_HUB_CONTRACT=0x60Ae865ee4C725cd04353b5AAb364553f56ceF82
LENS_PERIPHERY_CONTRACT=0xD5037d72877808cdE7F669563e9389930AF404E8
```

```
MUMBAI_RPC_URL=https://rpc-mumbai.matic.today # & also tried https://polygon-mainnet.g.alchemy.com/v2/MY_KEY
LENS_API=https://api-sandbox-mumbai.lens.dev
LENS_HUB_CONTRACT=0x7582177F9E536aB0b6c721e11f383C326F2Ad1D5
LENS_PERIPHERY_CONTRACT=0xa6bcF4398824A199965f89094796DFCcEa81b1a6
```

**Comment by zannis** [comment]
your alchemy api urls are pointing to polygon mainnet ;)

**Comment by apurvns** [comment]
Ohh I used mainnet url  🤐
Polygon testnet ->alchemy url worked 

Thanks @zannis

**Comment by zannis** [comment]
Cheers, closing this then! Have fun using the API and get in touch if you build something interesting! 🌞
