### ISSUE TITLE
Ability for a user to change the contentURI of their post

### ISSUE THREAD

**Issue by siddharthgowda** [lens-protocol/api-examples#93]
I was wondering if users can change the contentURI of their own post and if its in the in the smart contracts or API? For apps like twitter this is not really a big deal but if I wanted to post a blog on lens and I wanted to edit it later the only way I could do that is if I deleted the post and created a new post, losing all engagement the blog had already received.

**Comment by joshstevens19** [comment]
Hey, right now publication contentURI is immutable meaning you cant update it on-chain, we are working on a way to allow you to upload using a centralized link and migrate to IPFS after, this will allow you to edit, it's currently in the backlog.
