### ISSUE TITLE
authentication doesn’t login with a smart wallet

### ISSUE THREAD

**Issue by jheavejimenez** [lens-protocol/api-examples#95]
hi i'm currently playing around with lens api, does lens support sequence wallet(https://sequence.app/) ? because i'm getting this error when i try to sign in using sequence wallet
<img width="1123" alt="Screen Shot 2022-10-02 at 1 34 45 PM" src="https://user-images.githubusercontent.com/40889884/193439615-90185926-0660-4440-9278-a81d2c0a3809.png">

**Comment by joshstevens19** [comment]
https://github.com/lens-protocol/api-examples/issues/59
