### ISSUE TITLE
[Feature] Time of Collect in `WhoCollectedPublication` 

### ISSUE THREAD

**Issue by NelsonRodMar** [lens-protocol/api-examples#99]
Get the `createdAt` in the request [`WhoCollectedPublication`](https://docs.lens.xyz/docs/who-collected-publication) that return the DateTime of the time of collect.

**Comment by juangm** [comment]
The endpoint changed to [whoActedOnPublication](https://api-v2-docs.lens.xyz/#query-whoActedOnPublication) and the field `createdAt` was added there.
